### ISSUE TITLE
Ingredient Quantity

### ISSUE THREAD

**Issue by Kamiran79** [nss-evening-cohort-12/nutshell-moose#92]
# User Story
As a user, when I click on an ingredient, I should see the ingredient name, type and quantity.
# AC
**WHEN** the user clicks on an ingedient
it should look like the wireframe. With the quantity added to current view.
https://user-images.githubusercontent.com/42584830/88351143-f74bb880-cd1a-11ea-9f53-5825eea51c4b.png

# Dev Notes
* Add quantity to ingredient card.
Add quantity to add and edit ingredient fields.

**Comment by spotmonk** [comment]
closed by #112
